---
- type: replace
  path: /instance_groups/name=doppler/jobs/name=log-cache/properties/metrics?
  value:
    ca_cert: "((log_cache_metrics_tls.ca))"
    cert: "((log_cache_metrics_tls.certificate))"
    key: "((log_cache_metrics_tls.private_key))"
    server_name: log_cache_metrics

- type: replace
  path: /instance_groups/name=doppler/jobs/name=log-cache-cf-auth-proxy/properties/metrics?
  value:
    ca_cert: "((log_cache_cf_auth_proxy_metrics_tls.ca))"
    cert: "((log_cache_cf_auth_proxy_metrics_tls.certificate))"
    key: "((log_cache_cf_auth_proxy_metrics_tls.private_key))"
    server_name: log_cache_cf_auth_proxy_metrics

- type: replace
  path: /instance_groups/name=doppler/jobs/name=log-cache-gateway/properties/metrics?
  value:
    ca_cert: "((log_cache_gateway_metrics_tls.ca))"
    cert: "((log_cache_gateway_metrics_tls.certificate))"
    key: "((log_cache_gateway_metrics_tls.private_key))"
    server_name: log_cache_gateway_metrics

- type: replace
  path: /variables/name=metric_scraper_ca?
  value:
    name: metric_scraper_ca
    type: certificate
    options:
      is_ca: true
      common_name: metricScraperCA

- type: replace
  path: /variables/name=log_cache_metrics_tls?
  value:
    name: log_cache_metrics_tls
    type: certificate
    options:
      ca: metric_scraper_ca
      common_name: log_cache_metrics
      extended_key_usage:
      - server_auth

- type: replace
  path: /variables/name=log_cache_cf_auth_proxy_metrics_tls?
  value:
    name: log_cache_cf_auth_proxy_metrics_tls
    type: certificate
    options:
      ca: metric_scraper_ca
      common_name: log_cache_cf_auth_proxy_metrics
      extended_key_usage:
      - server_auth

- type: replace
  path: /variables/name=log_cache_gateway_metrics_tls?
  value:
    name: log_cache_gateway_metrics_tls
    type: certificate
    options:
      ca: metric_scraper_ca
      common_name: log_cache_gateway_metrics
      extended_key_usage:
      - server_auth
