---
- type: replace
  path: /releases/name=log-cache?
  value:
    name: log-cache
    version: latest

- type: replace
  path: /instance_groups/name=doppler/jobs/name=log-cache-syslog-server?
  value:
    release: log-cache
    name: log-cache-syslog-server
    properties:
      tls:
        cert: "((log_cache_syslog_server_tls.certificate))"
        key: "((log_cache_syslog_server_tls.private_key))"
      metrics:
        ca_cert: "((log_cache_syslog_server_metrics_tls.ca))"
        cert: "((log_cache_syslog_server_metrics_tls.certificate))"
        key: "((log_cache_syslog_server_metrics_tls.private_key))"
        server_name: log_cache_syslog_server_metrics

- type: replace
  path: /variables/name=syslog_drain_ca?
  value:
    name: syslog_drain_ca
    type: certificate
    options:
      is_ca: true
      common_name: syslogDrainCA

- type: replace
  path: /variables/name=log_cache_syslog_server_tls?
  value:
    name: log_cache_syslog_server_tls
    type: certificate
    options:
      ca: syslog_drain_ca
      common_name: "doppler.service.cf.internal"
      extended_key_usage:
      - server_auth

- type: replace
  path: /variables/name=metric_scraper_ca?
  value:
    name: metric_scraper_ca
    type: certificate
    options:
      is_ca: true
      common_name: metricScraperCA

- type: replace
  path: /variables/name=log_cache_syslog_server_metrics_tls?
  value:
    name: log_cache_syslog_server_metrics_tls
    type: certificate
    options:
      ca: metric_scraper_ca
      common_name: log_cache_syslog_server_metrics
      extended_key_usage:
      - server_auth

- type: remove
  path: /instance_groups/name=doppler/jobs/name=log-cache-nozzle?

- type: replace
  path: /addons/name=loggr-syslog-agent/jobs/name=loggr-syslog-agent/properties/aggregate_drains?
  value: "syslog-tls://doppler.service.cf.internal:6067"

- type: replace
  path: /addons/name=loggr-syslog-agent/jobs/name=loggr-syslog-agent/properties/drain_ca_cert?
  value: "((log_cache_syslog_server_tls.ca))"

# This can be removed when CAPI PR to handle container metrics from multiple envelopes is merged/released
# https://github.com/cloudfoundry/cloud_controller_ng/pull/1408
- type: replace
  path: /releases/name=capi
  value:
    name: capi
    version: latest