name: log-cache-blackbox

stemcells:
- alias: default
  os: ubuntu-xenial
  version: latest

releases:
- name: log-cache
  version: latest
- name: bpm
  version: latest

instance_groups:
- name: log-cache-blackbox
  azs:
  - z1
  instances: 1
  persistent_disk_type: 5GB
  vm_type: minimal
  stemcell: default
  networks:
  - name: default
  jobs:
  - name: log-cache-blackbox
    release: log-cache
    consumes:
      log-cache: {from: log-cache, deployment: default}
  - name: bpm
    release: bpm

update:
  canaries: 10
  max_in_flight: 10
  canary_watch_time: 30000-60000
  update_watch_time: 5000-60000
  serial: true
