name: log-cache

stemcells:
- alias: default
  os: ubuntu-xenial
  version: latest

releases:
- name: log-cache
  version: latest
- name: loggregator-agent
  version: latest
- name: bosh-dns
  version: latest
- name: bpm
  version: latest

addons:
- name: bosh-dns
  include:
    stemcell:
    - os: ubuntu-xenial
  jobs:
  - name: bosh-dns
    release: bosh-dns
- name: bpm
  include:
    stemcell:
    - os: ubuntu-xenial
  jobs:
  - name: bpm
    release: bpm

instance_groups:
- name: log-cache-scheduler
  azs:
  - z1
  - z2
  instances: 1
  persistent_disk_type: 5GB
  vm_type: minimal
  stemcell: default
  networks:
  - name: default
  jobs:
  - name: log-cache-scheduler
    release: log-cache
  - name: log-cache-prom-scraper
    release: loggregator-agent
    consumes:
      loggregator: {from: loggregator, deployment: loggregator}
    properties:
      metrics_urls: "http://localhost:6064/metrics"

- name: log-cache
  azs:
  - z1
  - z2
  instances: 1
  persistent_disk_type: 5GB
  vm_type: minimal
  stemcell: default
  networks:
  - name: default
  jobs:
  - name: log-cache
    release: log-cache
    provides:
      log-cache: {shared: true}
    properties:
      egress_port: 8080
      health_addr: "localhost:6060"
      tls:
        ca_cert: "((log_cache.ca))"
        cert: "((log_cache.certificate))"
        key: "((log_cache.private_key))"
  - name: log-cache-gateway
    release: log-cache
  - name: log-cache-nozzle
    release: log-cache
    consumes:
      reverse_log_proxy: {from: reverse_log_proxy, deployment: loggregator}
    properties:
      logs_provider:
        tls:
          ca_cert: "((log_cache_to_logs_provider.ca))"
          cert: "((log_cache_to_logs_provider.certificate))"
          key: "((log_cache_to_logs_provider.private_key))"
  - name: log-cache-prom-scraper
    release: loggregator-agent
    consumes:
      loggregator: {from: loggregator, deployment: loggregator}
    properties:
      metrics_urls: "http://localhost:6060/metrics,http://localhost:6061/metrics,http://localhost:6065/metrics"

variables:
- name: log_cache_to_logs_provider
  type: certificate
  options:
    ca: loggregator_ca
    common_name: log-cache
    extended_key_usage:
    - client_auth
- name: log_cache_to_loggregator_agent
  type: certificate
  options:
    ca: loggregator_ca
    common_name: log-cache
    extended_key_usage:
    - client_auth

- name: log_cache_ca
  type: certificate
  options:
    is_ca: true
    common_name: log-cache
- name: log_cache
  type: certificate
  options:
    ca: log_cache_ca
    common_name: log-cache
    alternative_names:
    - log_cache
    - log-cache
    - logcache
    extended_key_usage:
    - client_auth
    - server_auth

update:
  canaries: 10
  max_in_flight: 10
  canary_watch_time: 30000-60000
  update_watch_time: 5000-60000
  serial: true
