name: unit-tests
on:
  pull_request:
    branches:
    - main
    - v2.8.x
    - v2.1.x
  push:
    branches:
    - main
    - v2.8.x
    - v2.1.x
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - run: go vet ./...
        working-directory: src
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - run: go test -v -race ./...
        working-directory: src
  template-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v2
        with:
          bundler-cache: true
          ruby-version: 2.5
      - run: bundle exec rspec
